### ISSUE TITLE
ModuleNotFoundError: No module named 'carla'

### ISSUE THREAD

**Issue by USTC-ZS** [ShuaibinLi/RL_CARLA#2]
guys,This is my first contact with carla .Your readme is very detailed.But,Unfortunately, I have configured the virtual environment rl_carla as required . but erros still exist as follow:

```
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "/home/zs/RL_CARLA-main/train.py", line 4, in <module>
    from env_utils import ParallelEnv, LocalEnv
  File "/home/zs/RL_CARLA-main/env_utils.py", line 13, in <module>
    import  carla

ModuleNotFoundError: No module named 'carla'
```

I can import carla only in root directory  ,just like：

```
(rl_carla) zs@zs:~/RL_CARLA-main$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import carla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'carla'
>>>
(rl_carla) zs@zs:~/RL_CARLA-main$ cd ..
(rl_carla) zs@zs:~$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import `carla`
>>>
```

Please ！！！if you are chinese too,could tell me you qq or wechat?  send it to **sz1997@mail.ustc.edu.cn**  thank you!

**Comment by ShuaibinLi** [comment]
Maybe your PYTHONPATH changed(it happens sometime), you can check that with python(os.path, sys.path).
You need to add CARLA to your PYTHONPATH(according to which shell you are using, e.g. bash,zsh...), and check out it does not change while using carla package.
