### ISSUE TITLE
AttributeError: 'TorchModel' object has no attribute 'to'     (framework:torch)

### ISSUE THREAD

**Issue by YYan99** [ShuaibinLi/RL_CARLA#4]
```
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 64, in main
    critic_lr=CRITIC_LR)
  File "/home/yy/RL_CARLA/torch_base/torch_sac.py", line 42, in __init__
    self.model = model.to(device)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'TorchModel' object has no attribute 'to'
```
When I use torch, the error exist. How to solve It? Thanks.

**Comment by YuechengLiu** [comment]
please uninstall `paddlepaddle` in your current environment (make sure that only one deep-learning framework exists in your current environment).
