### ISSUE TITLE
AttributeError: 'TorchModel' object has no attribute 'get_actor_params'

### ISSUE THREAD

**Issue by ConaniLJH** [ShuaibinLi/RL_CARLA#7]
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main()
  File "train.py", line 66, in main
    critic_lr=CRITIC_LR)
  File "/home/conan/final project/RL_CARLA/torch_base/torch_sac.py", line 47, in __init__
    self.model.get_actor_params(), lr=actor_lr)
  File "/home/conan/anaconda3/envs/rl_carla/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'TorchModel' object has no attribute 'get_actor_params'

I  am using torch frame to train the model, but this error occurs.

**Comment by ShuaibinLi** [comment]
fixed
